@extends('superadmin.layout.app')

@section('title', 'Bug reports | ConvertPro')

@section('content')
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-zinc-500">Administration</p><h1 class="mt-1 text-3xl font-semibold">Bug reports</h1></div><flux:modal.trigger name="bug-report-filters"><flux:button variant="outline" icon="adjustments-horizontal">Filters</flux:button></flux:modal.trigger></div>
    <flux:modal name="bug-report-filters" variant="flyout" position="right"><form method="GET" class="space-y-5"><flux:heading size="lg">Filter reports</flux:heading><flux:select name="status" label="Status"><option value="">Any status</option>@foreach(['open', 'in_progress', 'resolved', 'closed'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</flux:select><div class="flex gap-2"><flux:button type="submit" variant="primary">Apply</flux:button><flux:button href="{{ route('admin.bug-reports.index') }}" variant="ghost">Clear</flux:button></div></form></flux:modal>
    <div class="mt-6 space-y-4">@forelse($reports as $report)<article class="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-lg font-semibold">{{ $report->subject }}</h2><p class="text-sm text-zinc-500">{{ $report->name }} · {{ $report->email }} · {{ $report->created_at->diffForHumans() }}</p></div><span class="rounded-full bg-zinc-100 px-2 py-1 text-xs font-medium dark:bg-zinc-800">{{ ucfirst(str_replace('_', ' ', $report->status)) }}</span></div><p class="mt-4 whitespace-pre-line text-sm text-zinc-700 dark:text-zinc-300">{{ $report->description }}</p>@can('manage bug reports')<form method="POST" action="{{ route('admin.bug-reports.update', $report) }}" class="mt-5 grid gap-3 border-t border-zinc-200 pt-4 sm:grid-cols-[12rem_1fr_auto] dark:border-zinc-800">@csrf @method('PUT')<flux:select name="status" label="Status">@foreach(['open', 'in_progress', 'resolved', 'closed'] as $status)<option value="{{ $status }}" @selected($report->status === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</flux:select><flux:input name="admin_notes" label="Admin notes" value="{{ $report->admin_notes }}" placeholder="Optional internal note" /><flux:button type="submit" variant="primary" class="self-end">Update</flux:button></form>@endcan</article>@empty<p class="rounded-2xl border border-dashed border-zinc-300 p-10 text-center text-zinc-500">No bug reports found.</p>@endforelse</div><div class="mt-5">{{ $reports->links() }}</div>
@endsection
