@extends('superadmin.layout.app')

@section('title', 'Users | ConvertPro')

@section('content')
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-medium text-zinc-500">Administration</p><h1 class="mt-1 text-3xl font-semibold">Users</h1></div><flux:button href="{{ route('admin.users.create') }}" variant="primary" icon="plus">Add user</flux:button></div>
    <div class="mt-6 flex items-center justify-between gap-3"><p class="text-sm text-zinc-500">{{ $users->total() }} total users</p><flux:modal.trigger name="user-filters"><flux:button variant="outline" icon="adjustments-horizontal">Filters</flux:button></flux:modal.trigger></div>
    <flux:modal name="user-filters" variant="flyout" position="right"><form method="GET" class="space-y-5"><flux:heading size="lg">Filter users</flux:heading><flux:input name="search" label="Search" value="{{ request('search') }}" placeholder="Name or email" /><flux:select name="status" label="Status"><option value="">Any status</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</flux:select><div class="flex gap-2"><flux:button type="submit" variant="primary">Apply</flux:button><flux:button href="{{ route('admin.users.index') }}" variant="ghost">Clear</flux:button></div></form></flux:modal>
    <div class="mt-4 overflow-hidden border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-zinc-200 bg-zinc-50 text-xs uppercase text-zinc-500 dark:border-zinc-800 dark:bg-zinc-950"><tr><th class="px-5 py-3">User</th><th class="px-5 py-3">Roles</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Actions</th></tr></thead><tbody class="divide-y divide-zinc-200 dark:divide-zinc-800">@forelse($users as $user)<tr><td class="px-5 py-4"><a class="font-medium hover:text-primary-600" href="{{ route('admin.users.show', $user) }}">{{ $user->name }}</a><p class="text-zinc-500">{{ $user->email }}</p></td><td class="px-5 py-4 text-zinc-600">{{ $user->roles->pluck('name')->join(', ') }}</td><td class="px-5 py-4"><span class="rounded-sm bg-zinc-100 px-2 py-1 text-xs font-medium dark:bg-zinc-800">{{ ucfirst($user->status) }}</span></td><td class="px-5 py-4"><div class="flex flex-wrap gap-2"><flux:button href="{{ route('admin.users.show', $user) }}" variant="outline" size="sm">View</flux:button><flux:button href="{{ route('admin.users.edit', $user) }}" variant="primary" size="sm">Edit</flux:button><form method="POST" action="{{ route('admin.users.destroy', $user) }}">@csrf @method('DELETE')<flux:button class="text-red-600" variant="ghost" size="sm" type="submit">Delete</flux:button></form></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-zinc-500">No users found.</td></tr>@endforelse</tbody></table></div><div class="border-t border-zinc-200 p-4 dark:border-zinc-800">{{ $users->links() }}</div></div>
@endsection
